#!/usr/bin/env python
# -*-coding: utf-8 -*-
# license removed for brevity
import rospy
import serial.tools.list_ports
import serial
import struct
#import queue
#import  threading 
import numpy as np
import time

import csv
import math

from LatLon import LatLon
from pyproj import Proj

from std_msgs.msg import Float64,Float32
from sensor_msgs.msg import NavSatFix


def trans(s):
    return "b'%s'" % ''.join('\\x%.2x' % x for x in s)
'''
def scan_com():
    com_name_list = list(serial.tools.list_ports.comports())
    com_number = len(com_name_list)
    if com_number == ttyS0:
        print("No ports available")
    else:
        for i in range(0,com_number) :
            print("Available port serial number",i,":",com_name_list[i])
        select_number=int(input ("Select available ports:"))
        print("Select ports",com_name_list[select_number])
        return com_name_list[select_number][0]
'''
com_name = '/dev/ttyS4'
def open_com(com_name):
    serialFd = serial.Serial(com_name, 9600, timeout=60)
    return serialFd     


	
"obtain longtitude and latitude quaterninon and ACC data from GPS+JY901"
class Connect():
    def __init__(self):
        self.serialFd = open_com(com_name)
        self.bys_dly = b'\x00'
        self.q4 = []
        self.acc = []
        self.gps = []
        self.angle = [0,0,0]
        self.finish = False
    def get_data(self):
        bys =self.serialFd.read()
        if (self.bys_dly == b'\x55') and (bys == b'\x59'):
            self.q4_get()
        if(self.bys_dly == b'\x55') and (bys == b'\x57'):
            self.gps_get()
        if(self.bys_dly == b'\x55') and (bys == b'\x53'):
            self.angle_get()
        if(self.bys_dly == b'\x55') and (bys == b'\x51'):
            self.acc_get()
        self.bys_dly = bys


    def q4_get(self):
        bys =b''
        for i in range(0,8):
            bys+=self.serialFd.read()
        data = struct.unpack('<4h',bys)
        data = np.array(data)
        data = data/32768.0
        self.q4 = data
        self.finish = True


    def acc_get(self):
        bys =b''
        for i in range(0,8):
            bys+=self.serialFd.read()
        data = struct.unpack('<4h',bys)
        data = np.array(data[:3])
        data =data/32768.0*4
        self.acc = data

    def gps_get(self):
        bys =b''
        for i in range(0,8):
            bys+=self.serialFd.read()
        data = struct.unpack('<2I',bys)
        data = np.array(data)
        data =data/10000000.0
        self.gps = data
    def angle_get(self):
        bys = b''
        for i in range(0,8):
            bys+=self.serialFd.read()
        data = struct.unpack('<4h',bys)
        data = np.array(data[:3])
        data = 360 -(data*180/32768+1)
        self.angle = data

#to x  y
def acc_trans(q,g):
    q = np.array(q)
    g = np.array(g).T
    c = np.array([
                        [1-2*(q[2]*q[2]+q[3]*q[3]),2*(q[1]*q[2]+q[0]*q[3])  ,2*(q[1]*q[3]-q[0]*q[2])],
                        [2*(q[1]*q[2]-q[0]*q[3])  ,1-2*(q[1]*q[1]+q[3]*q[3]),2*(q[2]*q[3]+q[0]*q[1])],
                        [2*(q[1]*q[3]+q[0]*q[2])  ,2*(q[2]*q[3]-q[0]*q[1])  ,1-2*(q[1]*q[1]+q[2]*q[2])]
                    ])
    c_I= np.linalg.inv(c)
    #g_neu=c_I @ g
    g_neu=np.dot(c_I,g)
    return g_neu


#60decimal to decimal
def degre(a):
    a = float(a)
    a=a*100
    t1=int(a/100)
    t2=(a%100)/60
    return (t1 + t2)

#latitude and longtitude to x and y
def gps_trans(lat,lon):
        lat = degre(lat)
        lon = degre(lon)
        #print('lat',lat)
        #print('lon',lon)
        d_x,d_y = NV.latlon_to_utm(lon,lat)
        return d_x,d_y




class Kl_fit:

    def __init__(self):
        t = 0.05
        self.X = np.array([[0],
                            [0],
                            [0]])
        self.F = np.array([[1,t,0.5*t*t],
                           [0,1,t],
                           [0,0,1]])
        self.P = np.array([[1,0,0],
                           [0,10,0],
                           [0,0,100] 
                            ])

        self.Q = np.array([[0.1,0,0],
                           [0,1,0],
                           [0,0,1]        
                                    ])

        self.H = np.array([[1,0,0],
                           [0,0,1]
                ])


        self.R = np.array([[10000,0],
                           [0,1000]
        ])
 
        self.I = np.array([[1,0,0],
                           [0,1,0],
                           [0,0,1]
                            ])
    def run_kl(self,pm,am):
        #x_ = self.F@self.X
        x_ = np.dot(self.F,self.X)
        #P_ = self.F@self.P@self.F.T + self.Q  
        P_ = np.dot(np.dot(self.F,self.P),self.F.T)+self.Q

        z = np.array([[pm],
                      [am]])
        
        #y = z - self.H@x_
        y = z - np.dot(self.H,x_)

        #S = self.H@P_@self.H.T + self.R
        S = np.dot(np.dot(self.H,P_),self.H.T) + self.R
        #K = P_@self.H.T@np.linalg.inv(S)
        K = np.dot(np.dot(P_,self.H.T),np.linalg.inv(S))

        #self.X = x_ + K@y
        self.X = x_ + np.dot(K,y)
        #self.P = (self.I - K@self.H)@P_
        self.P = np.dot((self.I - np.dot(K,self.H)),P_)
#latcoordinate transformation 
class Navigation(object):
    """docstring for ClassName"""
    def __init__(self, utm_zone=51,ellps='WGS84'):
        self.projection = Proj(proj='utm', zone=utm_zone, ellps='WGS84')
      
    def latlon_to_utm(self, lat, lon):
        """Returns (x, y) coordinates in metres"""
        return self.projection(lon, lat)

    def utm_to_latlon(self, x, y):
        """Returns a LatLon object"""
        lon, lat = self.projection(x, y, inverse=True)
        return lat, lon



if __name__ == '__main__':
    con = Connect()
    kl_x = Kl_fit()
    kl_y = Kl_fit()
    NV = Navigation()

    f = open('{}_gps_imu.csv'.format(time.time()),'w')

    rospy.init_node('ser_gps_imu',anonymous = True)
    position_pub = rospy.Publisher('position', NavSatFix, queue_size = 10)
    imu_pub = rospy.Publisher('heading', Float32, queue_size = 10)
    rate = rospy.Rate(10)
    msg_position = NavSatFix()
    heading = Float32()

    #while True:
    while not rospy.is_shutdown():
        while True:
            con.get_data()
            if con.finish == True:
                con.finish = False
                break
        heading = con.angle[2]
        print('heading',heading)
        g_neu=acc_trans(con.q4,con.acc)
        x_y = gps_trans(con.gps[0],con.gps[1])
        kl_x.run_kl(x_y[0],g_neu[0])
        kl_y.run_kl(x_y[1],g_neu[1])
        #print('x=',kl_x.X[0])
        #print('y=',kl_y.X[0])
    
        
        longitude,latitude = NV.utm_to_latlon(kl_x.X[0],kl_y.X[0])
        #longitude,latitude = NV.utm_to_latlon(x_y[0],x_y[1])
        print('longitude',longitude)
        print('latitude',latitude)

       # f = open('{}_gps_imu.csv'.format(time.time()),'w')
        f.write('{:.3f},{},{},{},{}\n'.format(time.time(),longitude[0],latitude[0],g_neu[0],g_neu[1]))
        #f.write('{},{:.5f},{:.5f}\n'.format(time.time,g_neu[0],g_neu[1]))

        msg_position.longitude = longitude
        msg_position.latitude = latitude
        position_pub.publish(msg_position)
        imu_pub.publish(heading)
        rate.sleep()
